### ISSUE TITLE
Restrict negative numbers in the tool

### ISSUE THREAD

**Issue by kocmitom** [kocmitom/MT-Thresholds#2]
When placing the difference, one may place negative sign (for degradations), which now is resolved as is. We should always use absolute value (but perhaps we should alert user?)

**Comment by zouharvi** [comment]
I saw some negative values during testing and "fixed it" by maxing it at 0: https://github.com/kocmitom/MT-Thresholds/blob/05e04f22416c690159047132067eb363b3480644/src/App.tsx#L98

However, that might be some other issue, likely stemming from precision loss or some deviations in the sigmoid inverse?

Could you show an example demonstrating your case? Happy to incorporate any formula changes.

**Comment by kocmitom** [comment]
This is an unusual hack, I am not sure if it solves any problem. Can we remove it and instead do "abs(user_input)", please?
Or maybe better, keep the negative sign:

accuracy = sign(user)*sigmoid(abs(user), params)

**Comment by kocmitom** [comment]
As for the example, try "-3" BLEU. It should behave like "3" BLEU, but having a negative sign in front of all results (this is for convenience, since the accuracy is always 0-100%)

**Comment by zouharvi** [comment]
> As for the example, try "-3" BLEU. It should behave like "3" BLEU, but having a negative sign in front of all results (this is for convenience, since the accuracy is always 0-100%)

That's a different problem. The reason why I added the `max` is that for low BLEU scores the corresponding deltas in e.g. COMET22 somehow became negative (and close to 0).

**Comment by kocmitom** [comment]
I see, that is a different problem, I didn't noticed before. So yes, there are two behaviour we want:
For low positive BLEU (or any metric that makes this) whenever other metrics would get negativ, clip them to 0.
For negative metric values that user types, use abs to calculate accuracy on positive delta

**Comment by zouharvi** [comment]
This clearly affects both the Python and Web tools.

Not sure if this is the same phenomenon, but consider:
```
mt-thresholds --delta bleu 0.45
```

We are asking what BLEU delta gives 45% accuracy. The output is 0.039, which is either false or not immediately intuitive.

**Comment by kocmitom** [comment]
It is the same phenomena, but I think we shouldn't allow asking lower than 50% because thats just a toss of a coin. There is no reason why you should want lower

**Comment by zouharvi** [comment]
Ok, added bounds check for the Python tool in b7fc759. Not deployed to PyPi yet.

> When placing the difference, one may place negative sign

The web bounds check weren't working properly because of a React bug. It's now fixed in bd98613 so that it's between 0 and 100. Deployed to gh pages.
