### ISSUE TITLE
MetricX models

### ISSUE THREAD

**Issue by ogencoglu** [kocmitom/MT-Thresholds#6]
Would be great to have metricx models in the benchmarks and online tool: https://github.com/google-research/metricx

**Comment by zouharvi** [comment]
Hi @ogencoglu, in 1.0.2 we added MetricX! :slightly_smiling_face: 

![image](https://github.com/user-attachments/assets/dc1b0ea3-6074-4ac1-9eef-a06d4cbdedc9)

(you need to click on "show other metrics")

**Comment by kocmitom** [comment]
we couldn't get the other MetricX models
