### ISSUE TITLE
COMET score scale

### ISSUE THREAD

**Issue by ZJaume** [kocmitom/MT-Thresholds#7]
Are the COMET score deltas computed from COMET scores multiplied by 100? Official COMET tool values often range between 0 and 1 (although sometimes values can go higher or lower than that) but often people reports the scores being multiplied by 100.  I guess the paper assumes scaled by 100? Because for 90% estimated accuracy COMET20 needs 3.45 delta, which is a huge difference if values are not scaled by 100.

**Comment by zouharvi** [comment]
Hi @ZJaume, indeed they are multiplied by 100, as stated in the web tool footer:
![image](https://github.com/user-attachments/assets/85f69dc5-8271-478d-9a0d-54b83c2ea1ff)

This is so that the scales across metrics are as unified as possible.

**Comment by ZJaume** [comment]
Was searching for that in the paper, didn't even read the full webpage. Thanks!

**Comment by kocmitom** [comment]
Good point about the paper, I remember mentioning it in the paper, but now I can't find the note about multiplication anywhere in the paper, it had to be omitted accidentaly during some rewrites.
